### ISSUE TITLE
`From<Vec>` for easier non-empty initialization

### ISSUE THREAD

**Issue by ronnodas** [droundy/append-only-vec#8]
Can `AppendOnlyVec` be made to implement `From<Vec>` and maybe also `FromIterator`? This would allow for easier initialization in the non-empty case via `vec![1,2,3].into` or `collect()` rather than pushing the items one by one. Perhaps having an `extend(&self, into_iter: impl IntoIterator<Item = T>)` could also make sense, especially if it would be more efficient.

**Comment by droundy** [comment]
These are definitely achievable requests, but right now I don't have time to handle this.  My suggestion would be to start by writing versions of these that give no performance benefit, and then as separate PRs introduce optimizations.

**Comment by droundy** [comment]
Okay, I found some time today after all, and have implemented these methods.  The `FromIterator` and `From<Vec<T>>` are indeed a bit more efficient than just calling `push` on all the elements, because we can relax some use of atomic operations since there cannot yet be concurrent access.

The `extend` I implemented is no more efficient than what you'd naively do calling push a bunch of times (which is what it does).

Both of these operations could theoretically be made more efficient, but it's a little hard to see how to do so without making other operations less efficient, since we currently use the length of the as the acquire/release operation to ensure memory safety, and it's hard (but not impossible) to "block process" the pushing operations.

**Comment by ronnodas** [comment]
Great! As you say, making `extend` block other pushes is maybe not the best idea because it can be passed an arbitrary iterator. Perhaps something like `Vec::extend_from_slice` could make more sense but I don't really have a use case in mind.
